### PR TITLE
Do not style html elements

### PR DESCRIPTION
**Pull request by ahoiroman**
Do not style html elements like body, a, ... as it could destroy an web-apps look & feel

### CODE REVIEW

**Comment by shubhadip** [comment]
so this global css is affecting the whole parent project ? is that what you are trying to say ?

**Comment by ahoiroman** [comment]
Yes. In my project I am using tailwindcss and I have to set `!important` to the font-type for the `<body>` to avoid this problem. I think it would be a more elegant solution to avoid adding styles to the html tags itself, but - if necessary - add them as classes like `.datepicker-body`

**Comment by shubhadip** [comment]
okay, ideally this shouldn't be happening bcoz css related to body shouldn't be bundled in library. Removing css completely will break the demo page of the library let me check if there are some unnecessary css bundling happening in the library.

**Comment by shubhadip** [comment]
this PR will probably fix this issue : https://github.com/shubhadip/vuejs3-datepicker/pull/31

**Pull request merged**
